// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOdb4tLVXsEIBxEGcLJUI4EPWfz_9Ztow',
    appId: '1:924312550788:web:06c7e97e2b541155e0f1d1',
    messagingSenderId: '924312550788',
    projectId: 'ping-pulse',
    authDomain: 'ping-pulse.firebaseapp.com',
    databaseURL: 'https://ping-pulse-default-rtdb.firebaseio.com',
    storageBucket: 'ping-pulse.firebasestorage.app',
    measurementId: 'G-X7MFZHFEG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiAzZx-oIPyP79Gqhh6qq9NL7cl7n6OBg',
    appId: '1:924312550788:android:a99b0a4ebfba142fe0f1d1',
    messagingSenderId: '924312550788',
    projectId: 'ping-pulse',
    databaseURL: 'https://ping-pulse-default-rtdb.firebaseio.com',
    storageBucket: 'ping-pulse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUvB4MpSav4Ml7IRR-NWOKR9ypSjJtlWQ',
    appId: '1:924312550788:ios:a11bae19d6a6e7bee0f1d1',
    messagingSenderId: '924312550788',
    projectId: 'ping-pulse',
    databaseURL: 'https://ping-pulse-default-rtdb.firebaseio.com',
    storageBucket: 'ping-pulse.firebasestorage.app',
    iosBundleId: 'com.example.urlManager',
  );
}
